### ISSUE TITLE
Inserting StringBuilder values

### ISSUE THREAD

**Issue by michallepicki** [michaeljones/gleam-templates#11]
Currently the `{{ name }}` syntax can be used to insert String values into the template. To insert StringBuilder values, one must issue unnecessary `string_builder.to_string` calls.

I think it could be useful to allow inserting StringBuilder values (probably through new syntax?). This would translate to `string_builder.append_builder` calls instead of `string_builder.append`. Could be useful especially when composing multiple templates.

**Comment by michaeljones** [comment]
Good point. Thanks for raising it. How do you think we could go about it? I guess some new syntax. Or we could use a with statement at the top to tell the system that something is a `StringBuilder` rather than a `String`.

We could use `{[ variable ]}` as the syntax as conceptually the `StringBuilder` is sort of a list of strings internally (I guess) so it has echoes of that. 

Otherwise maybe:
- `{{b:name}}` or `{{builder:name}}` to indicate a builder.
- `{{ *name }}` to kind of "splat" the builder into the string. 
- `{{ ...name }}` for similar reasons.
- `[[ name ]]` Similar to the top suggestion but embracing the double-ness.
- `{b name d}` for `b` for builder & `d` for symmetry :see_no_evil: 

Any thoughts or preferences? Probably `{[ name ]}` or `[[ name ]]` for me. Or `{{ ...name }}`

**Comment by michallepicki** [comment]
> Or we could use a with statement at the top to tell the system that something is a StringBuilder rather than a String.

I think this might be a bit limiting, e.g. I think it would be great to be able to call 
```
{% for user in users %}
    [[ user_template.render_builder(user) ]]
{% endfor %}
```

I like `[[ ]]` personally :)

edit: also 
> {b name d} for b for builder & d for symmetry :see_no_evil:

😆
